<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Versioning" Version="5.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Versioning.ApiExplorer" Version="5.1.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="7.2.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Modules\AuthService\AuthService.csproj" />
    <ProjectReference Include="..\Modules\ExamService\ExamService.csproj" />
    <ProjectReference Include="..\Modules\CourseService\CourseService.csproj" />
    <ProjectReference Include="..\Modules\ProctoringService\ProctoringService.csproj" />
    <ProjectReference Include="..\Modules\NotificationService\NotificationService.csproj" />
    <ProjectReference Include="..\Modules\ExamAttemptService\ExamAttemptService.csproj" />
    <ProjectReference Include="..\Modules\ResultService\ResultService.csproj" />
    <ProjectReference Include="..\Modules\AnalyticsService\AnalyticsService.csproj" />
    <ProjectReference Include="..\Modules\VideoClassesService\VideoClassesService.csproj" />
    <ProjectReference Include="..\Modules\QuestionBankService\QuestionBankService.csproj" />
    <ProjectReference Include="..\Modules\EnrollmentService\EnrollmentService.csproj" />
    <ProjectReference Include="..\Modules\WalletService\WalletService.csproj" />
  </ItemGroup>
</Project>
