using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ApiExplorer;
using Microsoft.IdentityModel.Tokens;
using Microsoft.OpenApi.Models;
using System.Text;

var builder = WebApplication.CreateBuilder(args);

// ==========================================
// CORS CONFIGURATION (ALLOW ANYWHERE)
// ==========================================
builder.Services.AddCors(options =>
{
    options.AddPolicy("AllowFrontend", policy =>
    {
        policy.AllowAnyOrigin()   // Allows requests from any origin
              .AllowAnyMethod()   // Allows any HTTP method (GET, POST, etc.)
              .AllowAnyHeader();  // Allows any HTTP headers
    });
});

builder.Services.AddApiVersioning(options =>
{
    options.DefaultApiVersion = new ApiVersion(1, 0);   // default v1
    options.AssumeDefaultVersionWhenUnspecified = true; // agar client version na de to default use ho
    options.ReportApiVersions = true;                   // response headers me supported versions show kare
});

builder.Services.AddVersionedApiExplorer(options =>
{
    options.GroupNameFormat = "'v'VVV"; // v1, v2, v3
    options.SubstituteApiVersionInUrl = true;
});


// ==========================================
// 1. JWT AUTHENTICATION CONFIGURATION
// ==========================================
var jwtSettings = builder.Configuration.GetSection("Jwt");
var key = Encoding.UTF8.GetBytes(jwtSettings["Key"] ?? "YourSuperSecretKeyForJWTTokenGeneration12345678901234567890");

builder.Services.AddAuthentication(options =>
{
    options.DefaultAuthenticateScheme = JwtBearerDefaults.AuthenticationScheme;
    options.DefaultChallengeScheme = JwtBearerDefaults.AuthenticationScheme;
})
.AddJwtBearer(options =>
{
    options.TokenValidationParameters = new TokenValidationParameters
    {
        ValidateIssuer = true,
        ValidateAudience = true,
        ValidateLifetime = true,
        ValidateIssuerSigningKey = true,
        ValidIssuer = jwtSettings["Issuer"],
        ValidAudience = jwtSettings["Audience"],
        IssuerSigningKey = new SymmetricSecurityKey(key)
    };
});


// ==========================================
// 2. REGISTER CORE SERVICES & CONTROLLERS
// ==========================================
builder.Services.AddControllers();
builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen(options =>
{
    // ==========================================
    // API VERSIONED SWAGGER DOCUMENTS
    // ==========================================

    // Swagger documents are configured using the
    // API version groups generated by ApiExplorer.
    options.SwaggerDoc("v1", new OpenApiInfo
    {
        Title = "Course Service API",
        Version = "v1",
        Description = "Course Service API - Version 1.0"
    });

    // If you add v2 later:
    //
    // options.SwaggerDoc("v2", new OpenApiInfo
    // {
    //     Title = "Course Service API",
    //     Version = "v2",
    //     Description = "Course Service API - Version 2.0"
    // });

    // ==========================================
    // SCHEMA ID
    // ==========================================

    options.CustomSchemaIds(type => type.FullName);

    // ==========================================
    // JWT AUTHENTICATION
    // ==========================================

    options.AddSecurityDefinition("Bearer", new OpenApiSecurityScheme
    {
        Name = "Authorization",
        Type = SecuritySchemeType.Http,
        Scheme = "bearer",
        BearerFormat = "JWT",
        In = ParameterLocation.Header,
        Description = "Enter your JWT token."
    });

    options.AddSecurityRequirement(new OpenApiSecurityRequirement
    {
        {
            new OpenApiSecurityScheme
            {
                Reference = new OpenApiReference
                {
                    Type = ReferenceType.SecurityScheme,
                    Id = "Bearer"
                }
            },
            Array.Empty<string>()
        }
    });

    // ==========================================
    // API VERSION GROUPING
    // ==========================================

    options.DocInclusionPredicate((documentName, apiDescription) =>
    {
        return apiDescription.GroupName == documentName;
    });
});

builder.Services.AddSignalR();
builder.Services.AddRazorPages();
builder.Services.AddHttpClient();


// ==========================================
// 3. REGISTER ALL MICROSERVICES DEPENDENCIES
// ==========================================

// --- AuthService ---
builder.Services.AddTransient<AuthService.Services.IEmailService, AuthService.Services.EmailService>();
builder.Services.AddTransient<AuthService.Services.IPhoneService, AuthService.Services.PhoneService>();
builder.Services.AddScoped<AuthService.Services.MongoDbService>();
builder.Services.AddScoped<AuthService.Services.AuthenticationService>();

// --- ExamService ---
builder.Services.AddScoped<ExamService.Services.MongoDbService>();
builder.Services.AddScoped<ExamService.Services.ExamManagementService>();

// --- ResultService ---
builder.Services.AddScoped<ResultService.Services.MongoDbService>();
builder.Services.AddScoped<ResultService.Services.EvaluationService>();

// --- ExamAttemptService ---
builder.Services.AddScoped<ExamAttemptService.Services.MongoDbService>();
builder.Services.AddScoped<ExamAttemptService.Services.AttemptManagementService>();

// --- NotificationService ---
builder.Services.AddScoped<NotificationService.Services.MongoDbService>();
builder.Services.AddScoped<NotificationService.Services.NotificationManagementService>();
builder.Services.AddScoped<NotificationService.Services.EmailService>();

// --- QuestionBankService ---
builder.Services.AddScoped<QuestionBankService.Services.MongoDbService>();
builder.Services.AddScoped<QuestionBankService.Services.QuestionService>();

// --- ProctoringService ---
builder.Services.AddScoped<ProctoringService.Services.MongoDbService>();
builder.Services.AddScoped<ProctoringService.Services.ProctoringManagementService>();
builder.Services.AddScoped<ProctoringService.Services.AIAnalysisService>();

// --- VideoClassesService ---
builder.Services.AddScoped<VideoClassesService.Services.MongoDbService>();
builder.Services.AddScoped<VideoClassesService.Services.LiveClassService>();
builder.Services.AddScoped<VideoClassesService.Services.ProgressTrackingService>();
builder.Services.AddScoped<VideoClassesService.Services.CommentService>();
builder.Services.AddScoped<VideoClassesService.Services.CourseManagementService>();

// --- CourseService  ---
builder.Services.AddSingleton<CourseService.Services.MongoDbService>();
builder.Services.AddScoped<CourseService.Services.CourseManagementService>();

var app = builder.Build();

app.Use(async (context, next) =>
{
    Console.WriteLine($"[API HIT] {DateTime.Now:HH:mm:ss} {context.Request.Method} {context.Request.Path}");
    await next();
    Console.WriteLine($"[API DONE] Status: {context.Response.StatusCode}");
});


// ==========================================
// 4. HTTP REQUEST PIPELINE (MIDDLEWARES)
// ==========================================
if (app.Environment.IsDevelopment())
{
    app.UseSwagger();
    
    // FIXED: Configured SwaggerUI to map the dropdown to the API Versions correctly
    app.UseSwaggerUI(options =>
    {
        var provider = app.Services.GetRequiredService<IApiVersionDescriptionProvider>();
        foreach (var description in provider.ApiVersionDescriptions)
        {
            options.SwaggerEndpoint($"/swagger/{description.GroupName}/swagger.json", $"API {description.GroupName.ToUpperInvariant()}");
        }
    });
}

// Enable CORS middleware before Authentication and Authorization
app.UseCors("AllowFrontend");

app.UseAuthentication();
app.UseAuthorization();

app.MapControllers();
app.MapRazorPages();


// ==========================================
// 5. MAP SIGNALR HUBS
// ==========================================
app.MapHub<ProctoringService.Hubs.ProctoringHub>("/hubs/proctoring");
app.MapHub<NotificationService.Hubs.NotificationHub>("/hubs/notifications");
app.MapHub<VideoClassesService.Hubs.LiveClassHub>("/hubs/liveclass");

app.Run();